name: Test - Heading One

on:
  workflow_dispatch:

env:
  POST_LIST_START_IDX: ${{ vars.POST_LIST_START_IDX }}
  POST_LIST_END_IDX: ${{ vars.POST_LIST_END_IDX }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Install Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 9
          run_install: true

      - name: Confirm env variables
        run: |
          echo "POST_LIST_START_IDX is $POST_LIST_START_IDX"
          echo "POST_LIST_END_IDX is $POST_LIST_END_IDX"

      - name: Run tests
        run: pnpm run test:heading-one

      - name: Upload report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ vars.POST_LIST_START_IDX }}-${{ vars.POST_LIST_END_IDX }}
          path: __tests__/report/report.json
          retention-days: 30
